name: pao_tracker
description: "A new Flutter project."
publish_to: "none" # don't publish

version: 1.0.0+1

environment:
  sdk: ^3.9.2

# -------------------------
# runtime dependencies
# -------------------------
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.0 # state management
  sqflite: ^2.2.8+5 # sqlite
  path_provider: ^2.0.15 # file paths
  path: ^1.8.3 # path utils
  intl: ^0.18.1 # i18n & formatting
  image_picker: ^1.2.0 # pick images
  flutter_native_splash: ^2.3.0
  shared_preferences: ^2.1.1

# -------------------------
# dev tools
# -------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # app icon generator

# -------------------------
# tool configs (root-level)
# -------------------------
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon.png
  
  # Android-specific
  android: true
  android_gravity: center  # Image position
  android_12:
    image: assets/icon.png
    color: "#FFFFFF"

  
  # iOS-specific  
  ios: true
  ios_content_mode: center  # Image positioning for iOS
  
  # Additional options
  fullscreen: true  # Hide status bar during splash

# -------------------------
# flutter section
# -------------------------
flutter:
  uses-material-design: true

  # include the whole assets folder
  assets:
    - assets/
